name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FC: gfortran-9
      CC: gcc-9

    steps:
    - uses: actions/checkout@v2
    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libmpich-dev
        sudo apt-get install libnetcdf-dev libnetcdff-dev netcdf-bin pkg-config
        sudo apt-get install doxygen
        python3 -m pip install gcovr
          
    - name: build and test
      run: |
        set -x
        pwd && ls -l
        mkdir build && cd build
        cmake .. -DENABLE_DOCS=Yes -DCMAKE_PREFIX_PATH=~ -DCMAKE_Fortran_FLAGS="-g -fprofile-arcs -ftest-coverage -O0"
        make -j2
        make VERBOSE=1 test
        export PATH="/home/runner/.local/bin:$PATH"
        ls -l
        gcovr -s $HOME/work/NCEPLIBS-ncio/NCEPLIBS-ncio/src -r .. --html-details -o test-coverage.html
        pwd
        ls -l

    - uses: actions/upload-artifact@v2
      if: ${{ matrix.os == 'ubuntu-latest' }}
      with:
        name: test-coverage
        path: NCEPLIBS-ncio/build/*.html
