name: Linux
on:
  push:
    branches:
    - develop
    paths-ignore:
    - README.md
  pull_request:
    branches:
    - develop
    paths-ignore:
    - README.md

jobs:
  Linux:
    runs-on: ubuntu-latest
    env:
      FC: mpifort
      CC: mpicc
      CPPFLAGS: "-I${HOME}/netcdf/include"
      LDFLAGS: "-L${HOME}/netcdf/lib"
      PATH: "${HOME}/netcdf/bin:$PATH"

    steps:

    - uses: actions/checkout@v2

    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libmpich-dev

    - name: cache-netcdf
      id: cache-netcdf
      uses: actions/cache@v2
      with:
        path: ~/netcdf
        key: netcdf-c-4.7.4-${{ runner.os }}2

    - name: build-hdf5
      if: steps.cache-netcdf.outputs.cache-hit != 'true'
      run: |
        wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.7/src/hdf5-1.10.7.tar.gz &> /dev/null
        tar -xzf hdf5-1.10.7.tar.gz
        pushd hdf5-1.10.7
        ./configure --prefix=${HOME}/netcdf --enable-parallel --disable-tools --disable-fortran --disable-cxx
        make -j2
        make install
           
    - name: build-netcdf-c
      if: steps.cache-netcdf.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/Unidata/netcdf-c/archive/refs/tags/v4.7.4.tar.gz
        tar -xzf v4.7.4.tar.gz
        cd netcdf-c-4.7.4
        ./configure --prefix=${HOME}/netcdf --disable-dap --disable-utilities
        make -j2
        make install

    - name: build-netcdf-fortran
      if: steps.cache-netcdf.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/Unidata/netcdf-fortran/archive/v4.5.3.tar.gz &> /dev/null
        tar -xzf v4.5.3.tar.gz
        pushd netcdf-fortran-4.5.3
        ./configure --prefix=${HOME}/netcdf
        make -j2
        make install   
       
    - name: build and test
      run: |
        mkdir build && cd build
        cmake -DCMAKE_PREFIX_PATH='~;~/netcdf' ..
        make -j2 VERBOSE=1
        ctest --output-on-failure
