# This is a CI workflow for the NCEPLIBS-ncio project.
#
# This workflow builds ncio with Spack, including installing with the "--test
# root" option to run the Ctest suite. It also has a one-off job that validates
# the recipe by ensuring that every CMake option that should be set in the
# Spack recipe is so set.
#
# Alex Richert, Sep 2023
name: Spack
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Spack:
    strategy:
      matrix:
        os: ["ubuntu-latest"]

    runs-on: ${{ matrix.os }}

    steps:

    - name: "Install OpenMPI"
      run: sudo apt install openmpi-bin libopenmpi-dev   
 
    - name: "Build Spack package"
      uses: NOAA-EMC/ci-test-spack-package@develop
      with:
        package-name: ncio
        package-variants: ^netcdf-c ~blosc ~szip ^openmpi
        custom-recipe: spack/package.py
        use-repo-cache: true
        spack-compiler: gcc
        repo-cache-key-suffix: ${{ matrix.os }}-1
        spack-externals: cmake gmake perl openmpi


  # This job validates the Spack recipe by making sure each cmake build option is represented
  recipe-check:
    runs-on: ubuntu-latest

    steps:
    
    - name: recipe-check
      uses: NOAA-EMC/ci-check-spack-recipe@develop
      with:
        recipe-file: package/spack/package.py
        cmakelists-txt: package/CMakeLists.txt
        ignore-list: ENABLE_DOCS
